AUTHOR: "Hewavitharana_19"

primers:
  FWD: GTGCCAGCMGCCGCGGTAA
  REV: ATTAGASACCCBDGTAGTCC

offset:
  FWD: 5
  REV: 4

phixdb: "phix_db"

THREADS: 8

taxonomy:
  template: silva_v138_mothur/silva.nr_v138.ng.fasta
  tax: silva_v138_mothur/silva.nr_v138.tax
